services:
  - type: web
    name: game-app
    env: node
    buildCommand: npm run build:render
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: game-db
          property: connectionString
    autoDeploy: false

databases:
  - name: game-db
    databaseName: gamedb
    user: gameuser
    region: oregon
    postgresMajorVersion: 15